name: azaharplus-emulator
base: core24
version: '2123.3-A'
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
summary: Open-source 3DS emulator project based on Citra.
description: |
  AzaharPlus is a fork of the Azahar 3DS emulator that restores some features.

  Each version is the same as the corresponding version of Azahar exept for these features:

  * Support of 3DS files. If a file works with earlier Citra forks, it works with AzaharPlus.
  * Ability to download system files from official servers. No need for an actual 3DS.
grade: stable
confinement: strict
icon: azahar.svg

apps:
  azaharplus-emulator:
    command: usr/bin/azahar
    desktop: usr/share/applications/org.azahar_emu.Azahar.desktop
    common-id: org.azahar_emu.Azahar
    environment:
      QT_QPA_PLATFORMTHEME: xdgdesktopportal
      LD_LIBRARY_PATH: $SNAP/lxqt-support-core24/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
      QT_PLUGIN_PATH: $SNAP/lxqt-support-core24/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins:$QT_PLUGIN_PATH
    extensions: [kde-neon-6]
    plugs:
      - unity7
      - screen-inhibit-control
      - audio-playback
      - network
      - network-bind
      - home
      - removable-media
      - mount-observe
      - joystick
      - bluez
      - udisks2

plugs:
  shared-memory:
    private: true
  lxqt-support-core24:
    content: lxqt-support-core24
    interface: content
    target: $SNAP/lxqt-support-core24
    default-provider: lxqt-support-core24

layout:
  /usr/share/color-schemes:
    symlink: $SNAP/lxqt-support-core24/usr/share/color-schemes
  /usr/share/Kvantum:
    symlink: $SNAP/lxqt-support-core24/usr/share/Kvantum

package-repositories:
  - type: apt
    url: http://origin.archive.neon.kde.org/user
    suites: [noble]
    components: [main]
    architectures: [arm64, amd64]
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D

parts:
  azaharplus-app:
    plugin: cmake
    source: https://github.com/AzaharPlus/AzaharPlus.git
    source-tag: AZAHAR_PLUS_2123_3_A
    build-packages:
      - clang
      - libsdl2-dev
      - spirv-tools
      - libduktape207
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_C_COMPILER=clang
      - -DCMAKE_CXX_COMPILER=clang++
      - -DCMAKE_LINKER=lld
      - -DENABLE_QT_TRANSLATION=ON
      - -DUSE_DISCORD_PRESENCE=OFF
      - -DUSE_SYSTEM_SDL2=ON
      - -DENABLE_OPENAL=OFF 
    override-build: |
      craftctl default
      sed -i 's|Name=Azahar|Name=AzaharPlus [Kyu]|' $CRAFT_PART_INSTALL/usr/share/applications/org.azahar_emu.Azahar.desktop

  dependencies:
    after: [azaharplus-app]
    plugin: nil
    stage-packages:
      - libsdl2-2.0-0
      - libdecor-0-0
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdecor-0.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libSDL2-2.0.so*
