name: azaharplus-emulator
base: core24
version: '2123.3-A'
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
summary: Open-source 3DS emulator project based on Citra.
description: |
  AzaharPlus is a fork of the Azahar 3DS emulator that restores some features.

  Each version is the same as the corresponding version of Azahar exept for these features:

  * Support of 3DS files. If a file works with earlier Citra forks, it works with AzaharPlus.
  * Ability to download system files from official servers. No need for an actual 3DS.
grade: stable
confinement: strict
compression: lzo

apps:
  azaharplus-emulator:
    command-chain:
      - snap/command-chain/gpu-2404-wrapper
      - snap/command-chain/desktop-launch6
    command: usr/bin/azahar
    desktop: usr/share/applications/org.azahar_emu.Azahar.desktop
    common-id: org.azahar_emu.Azahar
    environment:
      SNAP_DESKTOP_RUNTIME: $SNAP/kf6
      GTK_USE_PORTAL: "1"
      QT_VERSION: "6"
      QT_QPA_PLATFORM: xcb
      QT_QPA_PLATFORMTHEME: xdgdesktopportal
      LD_LIBRARY_PATH: $SNAP/lxqt-support/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
      QT_PLUGIN_PATH: $SNAP/lxqt-support/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins:$QT_PLUGIN_PATH
    plugs:
      - desktop
      - desktop-legacy
      - unity7
      - opengl
      - wayland
      - x11
      - screen-inhibit-control
      - audio-playback
      - network
      - network-bind
      - home
      - removable-media
      - mount-observe
      - joystick
      - bluez
      - udisks2

hooks:
  configure:
    command-chain:
      - snap/command-chain/hooks-configure-desktop

plugs:
  desktop:
    mount-host-font-cache: false
  gtk-2-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  kf6-core24:
    content: kf6-core24-all
    interface: content
    target: $SNAP/kf6
    default-provider: kf6-core24
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404
  shared-memory:
    private: true
  lxqt-support:
    content: lxqt-support
    interface: content
    target: $SNAP/lxqt-support
    default-provider: lxqt-support

layout:
  /usr/share/X11:
    symlink: $SNAP/kf6/usr/share/X11
  /usr/share/qt6:
    symlink: $SNAP/kf6/usr/share/qt6
  /usr/share/libdrm:
    bind: $SNAP/gpu-2404/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/gpu-2404/drirc.d
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/share/color-schemes:
    symlink: $SNAP/lxqt-support/usr/share/color-schemes
  /usr/share/Kvantum:
    symlink: $SNAP/lxqt-support/usr/share/Kvantum

package-repositories:
  - type: apt
    url: http://origin.archive.neon.kde.org/user
    suites: [noble]
    components: [main]
    architectures: [arm64, amd64]
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D

parts:
  azaharplus:
    plugin: cmake
    source: https://github.com/AzaharPlus/AzaharPlus.git
    source-tag: AZAHAR_PLUS_2123_3_A
    build-snaps:
      - kde-qt6-core24-sdk
      - kf6-core24-sdk
    build-packages:
      - libsdl2-dev
      - spirv-tools
    build-environment:
      - PATH: /snap/kde-qt6-core24-sdk/current/usr/bin:/snap/kf6-core24-sdk/current/usr/bin${PATH:+:$PATH}
      - XDG_DATA_DIRS: $CRAFT_STAGE/usr/share:/snap/kde-qt6-core24-sdk/current/usr/share:/snap/kf6-core24-sdk/current/usr/share:/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
      - XDG_CONFIG_HOME: $CRAFT_STAGE/etc/xdg:/snap/kde-qt6-core24-sdk/current/etc/xdg:/snap/kf6-core24-sdk/current/etc/xdg:/etc/xdg${XDG_CONFIG_HOME:+:$XDG_CONFIG_HOME}
      - LD_LIBRARY_PATH: /snap/kde-qt6-core24-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:/snap/kde-qt6-core24-sdk/current/usr/lib:/snap/kf6-core24-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:/snap/kf6-core24-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/blas:/snap/kf6-core24-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/lapack:/snap/kf6-core24-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libproxy:/snap/kf6-core24-sdk/current/usr/lib:$CRAFT_STAGE/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:$CRAFT_STAGE/usr/lib:$CRAFT_STAGE/lib/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
      - CMAKE_PREFIX_PATH: $CRAFT_STAGE;/snap/kde-qt6-core24-sdk/current;/snap/kf6-core24-sdk/current;/usr${CMAKE_PREFIX_PATH:+;$CMAKE_PREFIX_PATH}
      - CMAKE_FIND_ROOT_PATH: $CRAFT_STAGE;/snap/kde-qt6-core24-sdk/current;/snap/kf6-core24-sdk/current;/usr${CMAKE_FIND_ROOT_PATH:+;$CMAKE_FIND_ROOT_PATH}
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_C_COMPILER=clang
      - -DCMAKE_CXX_COMPILER=clang++
      - -DCMAKE_LINKER=lld
      - -DENABLE_QT_TRANSLATION=ON
      - -DUSE_DISCORD_PRESENCE=OFF
      - -DUSE_SYSTEM_SDL2=ON
    override-build: |
      craftctl default
      sed -i 's|Name=Azahar|Name=AzaharPlus [NyKyu]|' $CRAFT_PART_INSTALL/usr/share/applications/org.azahar_emu.Azahar.desktop
      sed -i 's|Icon=org.azahar_emu.Azahar|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/org.azahar_emu.Azahar.svg|' $CRAFT_PART_INSTALL/usr/share/applications/org.azahar_emu.Azahar.desktop
      sed -i 's|TryExec=azahar|TryExec=${SNAP}/usr/bin/azahar|' $CRAFT_PART_INSTALL/usr/share/applications/org.azahar_emu.Azahar.desktop
      sed -i 's|Exec=azahar %f|Exec=${SNAP}/usr/bin/azahar %f|' $CRAFT_PART_INSTALL/usr/share/applications/org.azahar_emu.Azahar.desktop

  dependencies:
    after: [azaharplus]
    plugin: nil
    stage-packages:
      - libsdl2-2.0-0
      - libdecor-0-0
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdecor-0.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libSDL2-2.0.so*

  command-chain:
    after: [dependencies]
    plugin: nil
    source: ./launcher
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/snap
      cp -r command-chain $CRAFT_PART_INSTALL/snap/
      chmod 777 $CRAFT_PART_INSTALL/snap/command-chain/*